workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest

      groups:
        - appstore     # add your group name here

    scripts:
      - name: Force clear cache
        script: |
          rm -rf $CM_BUILD_DIR/.pub-cache
          rm -rf $CM_BUILD_DIR/ios/Pods
          rm -rf $CM_BUILD_DIR/build

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa

    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
        team_id: $APP_STORE_TEAM_ID
        bundle_id: com.buildyourmatch.app
        submit_to_testflight: true
        submit_to_app_store: false
