workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build IPA with automatic code signing
  script: |
    xcode-project use-profiles
    xcode-project build-ipa \
      --workspace="ios/Runner.xcworkspace" \
      --scheme="Runner" \
      --dart-define=SUPABASE_URL=$SUPABASE_URL \
      --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
      --dart-define=RC_PUBLIC_SDK_KEY=$RC_PUBLIC_SDK_KEY

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: false
        submit_to_testflight: true
