workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore

    scripts:
      - name: Force clear cache
        script: |
          rm -rf $CM_BUILD_DIR/.pub-cache
          rm -rf $CM_BUILD_DIR/ios/Pods
          rm -rf $CM_BUILD_DIR/build

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifact_paths:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
