-- Core user prefs / chat / points / dice schema
alter table if exists public.users add column if not exists is_admin boolean default false;
alter table if exists public.users add column if not exists locale text default 'en';

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_a uuid references public.users(id) on delete cascade,
  user_b uuid references public.users(id) on delete cascade,
  created_at timestamptz default now(),
  closed_by_a boolean default false,
  closed_by_b boolean default false,
  consent_photo_a boolean default false,
  consent_photo_b boolean default false,
  consent_video_a boolean default false,
  consent_video_b boolean default false,
  photo_unlocked boolean default false,
  video_unlocked boolean default false
);
alter table public.conversations enable row level security;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade,
  sender_id uuid references public.users(id) on delete cascade,
  content text not null,
  created_at timestamptz default now()
);
alter table public.messages enable row level security;
create policy "participants read" on public.messages for select using (
  auth.uid() in (select user_a from conversations where id = conversation_id) or
  auth.uid() in (select user_b from conversations where id = conversation_id)
);
create policy "sender write" on public.messages for insert with check (auth.uid() = sender_id);

create table if not exists public.user_points (
  user_id uuid primary key references public.users(id) on delete cascade,
  available_points int not null default 0,
  total_earned int not null default 0,
  total_purchased int not null default 0,
  updated_at timestamptz default now()
);
alter table public.user_points enable row level security;
create policy "self points" on public.user_points for select using (auth.uid() = user_id);

create table if not exists public.point_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  kind text check (kind in ('earn','spend','purchase')) not null,
  amount int not null check (amount > 0),
  note text, ref_id text, created_at timestamptz default now()
);
alter table public.point_ledger enable row level security;
create policy "self ledger" on public.point_ledger for select using (auth.uid() = user_id);

create table if not exists public.user_preferences (
  user_id uuid primary key references public.users(id) on delete cascade,
  religion text, language text[], nationality text, occupation text,
  max_distance_km int default 50, filter_mode text default 'strict' check (filter_mode in ('strict','relaxed')),
  updated_at timestamptz default now()
);
alter table public.user_preferences enable row level security;
create policy "self prefs" on public.user_preferences for select using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.daily_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  date date not null, rolls int not null default 0, last_roll_at timestamptz,
  unique (user_id, date)
);
alter table public.daily_checkins enable row level security;
create policy "self read" on public.daily_checkins for select using (auth.uid() = user_id);
create policy "self insert" on public.daily_checkins for insert with check (auth.uid() = user_id);
create policy "self update" on public.daily_checkins for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- POINTS BALANCE PER USER
create table if not exists public.user_points (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0,
  updated_at timestamptz not null default now()
);

-- POINTS TRANSACTION LOG
create table if not exists public.points_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  reason text not null,
  meta jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- DAILY DICE ROLLS
create table if not exists public.daily_dice (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  rolls_used integer not null default 0,
  unique (user_id, date)
);

-- QUESTIONS TABLE (IF YOU DON'T ALREADY HAVE ONE)
create table if not exists public.questions (
  id bigserial primary key,
  text text not null,
  type text not null default 'open',       -- open, mcq, fill_blank, puzzle
  depth_level text not null default 'light', -- light, medium, deep
  category text default 'general'
);

-- USER ANSWERS
create table if not exists public.user_answers (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  answer_text text not null,
  created_at timestamptz not null default now()
);
-- SIMPLE DAILY RELATIONSHIP CROSSWORD
create table if not exists public.relationship_crosswords (
  id bigserial primary key,
  puzzle_date date not null,
  title text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.relationship_crossword_clues (
  id bigserial primary key,
  crossword_id bigint not null references public.relationship_crosswords(id) on delete cascade,
  clue_number integer not null,
  clue_text text not null,
  answer text not null, -- store uppercase, no spaces
  created_at timestamptz not null default now()
);
